### ISSUE TITLE
Doesn't work with Sublime Text 3 (buid 3047)

### ISSUE THREAD

**Issue by chinhodado** [welovewordpress/SublimeHtmlTidy#31]
When I `ctrl + shift + P`, there's no `Tidy HTML` option

**Comment by firedev** [comment]
Same here, please help

**Comment by changeableface** [comment]
Same here. Doesn't work with Stable 3047
Running on Ubuntu 13.04 64bit. 

Mapped to crtl+shift+r.

**Comment by davidbitton** [comment]
In the console, I see the following:

`
reloading plugin HtmlTidy.html_tidy
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "html_tidy in /Users/bittond/Library/Application Support/Sublime Text 3/Installed Packages/HtmlTidy.sublime-package", line 194
    print "HTMLTidy: using Tidy found here: " + tidypath
                                            ^
SyntaxError: invalid syntax
`

So something is up.

**Comment by cviebrock** [comment]
ST3 support would be nice ... :+1:

**Comment by steinmb** [comment]
+1 to ST3 support :)

**Comment by kevinsperrine** [comment]
I threw together some rough ST3 support in this commit last night: 3fbb660e98dbf0e23d7ec76b430abe3e87bb0bd5. It's only been tested on OSX 10.9. Issue #32

**Comment by welovewordpress** [comment]
@kevinsperrine thanks a lot for your work, just one question before I merge it: Has this been tested on ST2 yet?

If anyone would like to fork this and maintain a ST3 version of this plugin, I'd greatly appreciate it - I'm not actually a python coder and if there are separate versions for ST2 and ST3, it would be less testing effort for whoever maintains one of them.

**Comment by kevinsperrine** [comment]
No, this has been tested on ST3 only. I only use ST3, so ST2 support never even crossed my mind.

**Comment by welovewordpress** [comment]
I'm afraid it doesn't seem to work with ST2 - I get the following error in a new tab:

```
Had a problem communicating with the webservice: 'module' object has no attribute 'parse'
```

I still think it would be best to maintain a separate version for ST2. Would you be able to take care of that?

Since plugins can be marked as ST2 or ST3 compatible only in Package Control now, you should submit your fork as ST3 compatible and this version here will stay around for people still using ST2.

Or is there anyone else who would volunteer for maintaining a version for ST3?
